<?php $title = 'Enable Two-Factor Authentication'; ob_start();

$pdfPath = base_path('vendor/tcpdf/tcpdf.php');
$qr = null;
if (file_exists($pdfPath)) {
    require_once $pdfPath;
    require_once base_path('vendor/tcpdf/tcpdf_barcodes_2d.php');
    try {
        $barcode = new \TCPDF2DBarcode($uri, 'QRCODE,H');
        $svg = $barcode->getBarcodeSVGcode(3, 3, '#000000');
        if (preg_match('/<svg[\s\S]*<\/svg>/', $svg, $m)) {
            $qr = str_replace(['<?xml version="1.0" standalone="no"?>', '<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">'], '', $m[0]);
        }
    } catch (\Throwable $e) {
        $qr = null;
    }
}
?>
<div class="row justify-content-center">
    <div class="col-md-7">
        <div class="card">
            <div class="card-header"><i class="bi bi-shield-plus"></i> Enable Two-Factor Authentication</div>
            <div class="card-body">
                <?php $error = session_flash('error'); ?>
                <?php if ($error): ?><div class="alert alert-danger py-2"><?= htmlspecialchars($error) ?></div><?php endif; ?>

                <ol class="mb-3">
                    <li>Install an authenticator app on your phone (Google Authenticator, Microsoft Authenticator, Authy, etc.).</li>
                    <li>Scan the QR code below, or manually enter the secret key.</li>
                    <li>Enter the 6-digit code generated by the app and confirm with your password.</li>
                </ol>

                <div class="text-center mb-3">
                    <?php if ($qr): ?>
                        <?= $qr ?>
                    <?php else: ?>
                        <div class="alert alert-warning">QR code could not be generated. Use the manual secret key below.</div>
                    <?php endif; ?>
                </div>

                <div class="text-center mb-3">
                    <div class="text-muted small mb-1">Manual secret key</div>
                    <code class="bg-light p-2 rounded d-inline-block"><?= htmlspecialchars($secret) ?></code>
                </div>

                <form method="POST" action="/profile/2fa/enable">
                    <?= csrf_field() ?>
                    <div class="mb-3">
                        <label class="form-label">Verification Code</label>
                        <input type="text" name="code" class="form-control" placeholder="6-digit code" inputmode="numeric" maxlength="8" required autofocus>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Confirm Password</label>
                        <input type="password" name="password" class="form-control" placeholder="Your current password" required>
                    </div>
                    <button type="submit" class="btn btn-primary"><i class="bi bi-check-circle"></i> Enable 2FA</button>
                    <a href="/profile" class="btn btn-outline-secondary">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
<?php $content = ob_get_clean(); require __DIR__ . '/../layouts/app.php'; ?>
